# Generated by Django 3.1.5 on 2021-01-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
