# Generated by Django 3.1.5 on 2021-01-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='carousels',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='srvices',
            new_name='photo',
        ),
    ]
